
CREATE TABLE CURSO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	MENSALIDADE DECIMAL
);

CREATE TABLE ALUNO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	SEXO CHAR CHECK(SEXO IN ('M', 'F')) NOT NULL,
	IDADE SMALLINT NOT NULL,
        DOCUMENTO VARCHAR UNIQUE,
        ID_CURSO INTEGER REFERENCES CURSO(ID)
);

CREATE TABLE DISCIPLINA (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
        ID_CURSO INTEGER REFERENCES CURSO(ID)
);

CREATE TABLE NOTA (
	ID SERIAL PRIMARY KEY,
	ID_ALUNO INTEGER REFERENCES ALUNO(ID) ON DELETE CASCADE,
	ID_DISCIPLINA INTEGER REFERENCES DISCIPLINA(ID) ON DELETE CASCADE,
        NP1 INTEGER,
        NP2 INTEGER,
        SUB INTEGER,
        EXAME INTEGER
);

