CREATE TABLE ALUNO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	SEXO CHAR CHECK(SEXO IN ('M', 'F')) NOT NULL,
	IDADE SMALLINT NOT NULL
);

CREATE TABLE CURSO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	MENSALIDADE DECIMAL
);

CREATE TABLE DISCIPLINA (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	OPTATIVA BOOLEAN DEFAULT FALSE
);

CREATE TABLE SALA (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);

CREATE TABLE PROFESSOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	NIVEL VARCHAR CHECK (NIVEL IN ('GRADUADO', 'ESPECIALISTA', 'MESTRE', 'DOUTOR', 'PHD')),
	SALARIO DECIMAL
);

CREATE TABLE TURMA (
	ID SERIAL PRIMARY KEY,
	ID_CURSO INTEGER REFERENCES CURSO(ID) ON DELETE CASCADE,
	ID_SALA INTEGER REFERENCES SALA(ID) ON DELETE SET NULL,
	NOME VARCHAR NOT NULL,
	PERIODO CHAR CHECK(PERIODO IN ('M', 'T', 'N')) NOT NULL,
	ANO_INICIO SMALLINT DEFAULT DATE_PART('year', CURRENT_DATE) NOT NULL,
	SEMESTRE SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE AULA (
	ID_TURMA INTEGER REFERENCES TURMA(ID) ON DELETE CASCADE,
	ID_PROFESSOR INTEGER REFERENCES PROFESSOR(ID) ON DELETE SET NULL,
	ID_CURSO INTEGER REFERENCES CURSO(ID) ON DELETE CASCADE,
	ID_DISCIPLINA INTEGER REFERENCES DISCIPLINA(ID) ON DELETE CASCADE NOT NULL,
	DIA_SEMANA INTEGER NOT NULL DEFAULT 1,
	HORA_INICIO TIME,
	HORA_FIM TIME
);

CREATE TABLE MATRICULA (
	ID SERIAL PRIMARY KEY,
	ID_ALUNO INTEGER REFERENCES ALUNO(ID) ON DELETE CASCADE,
	ID_TURMA INTEGER REFERENCES TURMA(ID) ON DELETE SET NULL,
    DESCONTO INTEGER,
	ATIVO BOOLEAN DEFAULT TRUE,
	DATA_MATRICULA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_FINALIZADO TIMESTAMP DEFAULT NULL
);

CREATE TABLE NOTA (
	ID_MATRICULA INTEGER REFERENCES MATRICULA(ID) ON DELETE CASCADE,
	ID_DISCIPLINA INTEGER REFERENCES DISCIPLINA(ID) ON DELETE CASCADE,
	NOME VARCHAR NOT NULL,
	TIPO VARCHAR CHECK (TIPO IN ('AVALIACAO', 'TRABALHO'))
)

ALTER TABLE ALUNO ADD COLUMN DOCUMENTO VARCHAR UNIQUE;